#%RAML 1.0 SecurityScheme
type: x-custom
description: "This security scheme authenticates the source of an API call by requiring the calling application to provide credentials, in the form of a Client ID and Client Secret, in the request headers."
describedBy:
  queryParameters:
    testParam:
      description: Test query parameter
      type: string
      example: x-test-value
  headers:
    Client-Id:
      description: "A valid Client ID that uniquely identifies the consuming application"
      type: string
      example: "283a6722121141feb7a929793d5c"
    Client-Secret:
      description: "A secret key, known only to the consuming application, which can be used to verify its identity"
      type: string
      example: "1421b7a929793d51fe283a67221c"
