#%RAML 1.0 Trait
description: Orderable endpoint query parameters
queryParameters:
  orderBy:
    description: |
      Order by field: <<fieldsList>>
    type: string
    required: false
  order:
    description: Order
    enum: [desc, asc]
    default: desc
    required: false