#%RAML 1.0 Trait
description: Secures endpoint by client_it and client_secret headers
headers:
  client_id:
    required: true
    description: client_id
    examples:
      example:
        value: a0aa00a0a0aa00a0
  client_secret:
    required: true
    description: client_secret
    examples:
      example:
        value: b1bb11b1b1bb11b1